# Sync official Cloudflare IP ranges into nginx/real-ip.conf
$ErrorActionPreference = "Stop"
$Root = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$V4 = Join-Path $Root "ips-v4.txt"
$V6 = Join-Path $Root "ips-v6.txt"
$Out = Join-Path $Root "nginx\real-ip.conf"

(Invoke-WebRequest -Uri "https://www.cloudflare.com/ips-v4" -UseBasicParsing).Content.Trim() | Set-Content $V4
(Invoke-WebRequest -Uri "https://www.cloudflare.com/ips-v6" -UseBasicParsing).Content.Trim() | Set-Content $V6

$lines = @(
    "# Auto-generated by platform/cloudflare/scripts/sync-ips.ps1",
    "# Cloudflare real client IP. See ADR-0064.",
    "real_ip_header CF-Connecting-IP;"
)
foreach ($cidr in (Get-Content $V4)) {
    if ($cidr.Trim()) { $lines += "set_real_ip_from $($cidr.Trim());" }
}
foreach ($cidr in (Get-Content $V6)) {
    if ($cidr.Trim()) { $lines += "set_real_ip_from $($cidr.Trim());" }
}
$lines | Set-Content $Out

$GatewayOut = Join-Path (Resolve-Path (Join-Path $Root "..\..\gateway-edge\cloudflare")).Path "real-ip.conf"
Copy-Item $Out $GatewayOut -Force
Write-Host "Wrote $Out and copied to gateway-edge/cloudflare/real-ip.conf"
