#!/usr/bin/env bash
# Sync official Cloudflare IP ranges → nginx real-ip.conf
# Run periodically (cron monthly) — Cloudflare publishes updates at cloudflare.com/ips-v4
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
V4="$ROOT/ips-v4.txt"
V6="$ROOT/ips-v6.txt"
OUT="$ROOT/nginx/real-ip.conf"

curl -fsSL "https://www.cloudflare.com/ips-v4" -o "$V4"
curl -fsSL "https://www.cloudflare.com/ips-v6" -o "$V6"

{
  echo "# Auto-generated by platform/cloudflare/scripts/sync-ips.sh — do not edit by hand."
  echo "# Cloudflare real client IP (free CDN / proxy). See ADR-0064."
  echo "real_ip_header CF-Connecting-IP;"
  while IFS= read -r cidr; do
    [[ -z "$cidr" ]] && continue
    echo "set_real_ip_from $cidr;"
  done < "$V4"
  while IFS= read -r cidr; do
    [[ -z "$cidr" ]] && continue
    echo "set_real_ip_from $cidr;"
  done < "$V6"
} > "$OUT"

echo "Wrote $OUT ($(wc -l < "$OUT") lines)"
